steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo Branch Name: $BRANCH_NAME'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo Commit SHA: $COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo Branch Name through git command: $(git symbolic-ref --short HEAD)'
