steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo Branch Name: $BRANCH_NAME'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo Vommit Sha: $COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo Revision ID: $REVISION_ID'
   - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo Branch Name through git command: $(git symbolic-ref --short HEAD)'
