steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - ' echo $BRANCH_NAME'
      - ' echo this is a test'
